/**
 * Interfaces for every external service. Each has a Mock* (deterministic, offline) and a Live*
 * implementation. Agents and the orchestrator depend ONLY on these interfaces.
 * CONTRACT FILE: owned by the foundation. Builders may ADD optional members, never change existing ones.
 */
import type { ProductType, TrademarkHit } from '../domain/types.ts';

/* ---------------------------------- Etsy ---------------------------------- */

export interface EtsyListingSummary {
  listingId: number;
  title: string;
  tags: string[];
  price: { amount: number; currency: string }; // amount in major units (e.g. 24.99)
  numFavorers: number;
  views: number | null; // window undocumented by Etsy: compare relatively only
  createdAt: string; // ISO
  state: 'active' | 'draft' | 'inactive' | 'sold_out' | 'expired';
}

export interface EtsySearchResult {
  count: number; // total matching active listings (competition signal)
  results: EtsyListingSummary[];
}

export interface EtsyReceiptLine {
  receiptId: number;
  listingId: number;
  quantity: number;
  priceAmount: number; // major units, shop currency
  currency: string;
  createdAt: string;
}

export interface EtsyClient {
  /** Public search of active listings (competition + demand signals). Offset is capped at 12,000 by Etsy. */
  searchActiveListings(q: { keywords: string; limit?: number; offset?: number }): Promise<EtsySearchResult>;
  getListing(listingId: number): Promise<EtsyListingSummary>;
  /** Shop's own listings in a state (e.g. drafts created by Printify). */
  listShopListings(q: { state: 'active' | 'draft' | 'inactive'; limit?: number }): Promise<EtsyListingSummary[]>;
  /** Approve = state 'active'. Retire = should_auto_renew false. */
  updateListing(listingId: number, patch: { state?: 'active' | 'inactive'; shouldAutoRenew?: boolean }): Promise<void>;
  /** Sold lines since a unix timestamp (seconds). */
  getReceiptLines(q: { minCreated: number }): Promise<EtsyReceiptLine[]>;
}

/* -------------------------------- Printify -------------------------------- */

export interface PrintifyVariantCost {
  variantId: number;
  title: string; // e.g. "Black / M"
  costUsd: number; // base cost, major units
}

export interface PrintifyCatalogEntry {
  productType: ProductType;
  blueprintId: number;
  printProviderId: number;
  variants: PrintifyVariantCost[];
  shippingFirstItemUsd: number; // to the target market
  /** Print area in px for the main placeholder ('front'). */
  printArea: { position: string; widthPx: number; heightPx: number };
}

export interface PrintifyProductInput {
  title: string;
  description: string;
  tags: string[];
  blueprintId: number;
  printProviderId: number;
  variants: { id: number; priceCents: number; isEnabled: boolean }[];
  /** Image id returned by uploadImage, placed on the front placeholder. */
  imageId: string;
  printPosition: string; // 'front'
}

export interface PrintifyProduct {
  id: string;
  title: string;
  /** Mockup image URLs generated by Printify (https only). */
  mockupUrls: string[];
  /** Set after a successful publish to Etsy. */
  external: { id: string; handle: string | null } | null;
  isLocked: boolean;
}

export interface PrintifyClient {
  getCatalogEntry(productType: ProductType): Promise<PrintifyCatalogEntry>;
  uploadImage(input: { fileName: string; contentsBase64: string }): Promise<{ id: string }>;
  createProduct(input: PrintifyProductInput): Promise<{ id: string }>;
  getProduct(productId: string): Promise<PrintifyProduct>;
  /** Publishes to the connected Etsy shop. With the Etsy connection in manual mode this creates a DRAFT. */
  publishProduct(productId: string): Promise<void>;
}

/* -------------------------------- Trademark ------------------------------- */

export interface TrademarkClient {
  /** Word-mark search (exact + wildcard handled by the implementation). Returns live and dead marks. */
  search(term: string): Promise<TrademarkHit[]>;
}

/* ------------------------------ Image generation -------------------------- */

export interface GeneratedImage {
  bytes: Uint8Array;
  mimeType: 'image/png';
  model: string;
  seed: number | null;
}

export interface ImageGenClient {
  generate(req: {
    prompt: string;
    /** 'vector_illustration' | 'typography' | free-form style hint */
    style: string;
    transparentBackground: boolean;
    widthPx: number;
    heightPx: number;
    seed?: number;
  }): Promise<GeneratedImage>;
}

/* --------------------------------- Trends --------------------------------- */

export interface TrendSignalInput {
  source: string;
  keyword: string;
  region: string;
  score: number; // 0..100 relative within the source
  growth: number | null;
}

export interface TrendSource {
  readonly name: string;
  /** Returns [] (never throws) when the source is unavailable, e.g. no Pinterest access. */
  fetchSignals(q: { market: 'US'; today: string }): Promise<TrendSignalInput[]>;
}

/* --------------------------------- Storage -------------------------------- */

export interface BlobStorage {
  /** Keys are relative, [a-z0-9/_.-] only, no '..'. Implementations MUST reject anything else. */
  put(key: string, bytes: Uint8Array, mimeType: string): Promise<void>;
  get(key: string): Promise<{ bytes: Uint8Array; mimeType: string } | null>;
  delete(key: string): Promise<void>;
}

/* ------------------------------ Image inspection -------------------------- */

export interface ImageInspection {
  format: string; // 'png' | 'jpeg' | ...
  widthPx: number;
  heightPx: number;
  dpi: number | null;
  hasAlpha: boolean;
  colorSpace: string; // 'srgb' expected
  /** Share of pixels whose alpha is strictly between 0 and 255 (semi-transparent). */
  semiTransparentShare: number;
}

export interface ImageTools {
  inspect(bytes: Uint8Array): Promise<ImageInspection>;
  /** Resize/convert to an exact print spec (PNG, sRGB, DPI metadata). Never upscales more than 4x. */
  toPrintFile(bytes: Uint8Array, spec: { widthPx: number; heightPx: number; dpi: number }): Promise<Uint8Array>;
}

/* --------------------------- Local GPU (RTX 3060) ------------------------- */

/**
 * One 12 GB GPU is shared by Ollama (LLM, ~8 GB for gemma4:12b at 16k ctx) and the imagegen sidecar
 * (FLUX.2 klein 4B with CPU offload, BiRefNet, Real-ESRGAN). They cannot both hold VRAM at once.
 * Every GPU call goes through withGpu(): calls are serialised, and before switching owner the coordinator
 * asks the previous owner to release VRAM (Ollama: keep_alive 0; sidecar: POST /unload).
 */
export type GpuOwner = 'llm' | 'image';

export interface GpuCoordinator {
  withGpu<T>(owner: GpuOwner, fn: () => Promise<T>): Promise<T>;
}

/** AI upscaler (Real-ESRGAN x4 on the sidecar). Output is PNG; alpha preserved. */
export interface ImageUpscaler {
  upscale(bytes: Uint8Array, factor: 2 | 4): Promise<Uint8Array>;
}

/** Fetches an image from a third-party URL through the SSRF-safe allowlisted fetcher. */
export type AllowlistedImageFetcher = (url: string) => Promise<{ bytes: Uint8Array; mimeType: string }>;

/* ------------------------------ Bundle ------------------------------------ */

export interface Integrations {
  etsy: EtsyClient;
  printify: PrintifyClient;
  trademark: TrademarkClient;
  imageGen: ImageGenClient;
  trendSources: TrendSource[];
  storage: BlobStorage;
  imageTools: ImageTools;
  /** Present for the local GPU stack (always present in mock mode as a no-op serialiser). */
  gpu: GpuCoordinator;
  /** Present when the imagegen sidecar is configured (and in mock mode). */
  upscaler: ImageUpscaler | null;
  /** For Printify mockup URLs (QA vision check). */
  fetchImage: AllowlistedImageFetcher;
}
